package io.github.gobi12b.reclaimlife.ui.theme

import androidx.compose.ui.graphics.Color

// Nature palette — leaf green, bark brown, sunlight gold. Growth over feed-colored orange.
val GreenLight = Color(0xFF3F7D4A)
val OnGreenLight = Color(0xFFFFFFFF)
val BrownLight = Color(0xFF8B5E34)
val OnBrownLight = Color(0xFFFFFFFF)
val GoldLight = Color(0xFFD9A441)
val OnGoldLight = Color(0xFF3A2900)
val BackgroundLight = Color(0xFFF6F4EC)
val OnBackgroundLight = Color(0xFF23281F)
val SurfaceVariantLight = Color(0xFFE6E2D3)
val OnSurfaceVariantLight = Color(0xFF55594C)
val ErrorLight = Color(0xFFBA1A1A)
val GreenContainerLight = Color(0xFFC8EBCB)
val OnGreenContainerLight = Color(0xFF0B3818)
val BrownContainerLight = Color(0xFFF5DDC4)
val OnBrownContainerLight = Color(0xFF2E1B06)
val GoldContainerLight = Color(0xFFFFE6A8)
val OnGoldContainerLight = Color(0xFF3A2900)
val OutlineLight = Color(0xFF737A6B)
val OutlineVariantLight = Color(0xFFC6CABB)
// Warm, leaf-tinted neutrals for cards, so they sit in the palette instead of Material's default grey-violet.
val SurfaceLowestLight = Color(0xFFFFFFFF)
val SurfaceLowLight = Color(0xFFF1EFE5)
val SurfaceContainerLight = Color(0xFFECEADF)
val SurfaceHighLight = Color(0xFFE6E4D9)
val SurfaceHighestLight = Color(0xFFE0DED2)

val GreenDark = Color(0xFF8FD19E)
val OnGreenDark = Color(0xFF0B3818)
val BrownDark = Color(0xFFD8B08A)
val OnBrownDark = Color(0xFF3F2A12)
val GoldDark = Color(0xFFF0C868)
val OnGoldDark = Color(0xFF402D00)
val BackgroundDark = Color(0xFF141A14)
val OnBackgroundDark = Color(0xFFE3E8DD)
val SurfaceVariantDark = Color(0xFF3C4234)
val OnSurfaceVariantDark = Color(0xFFC4C8B8)
val ErrorDark = Color(0xFFFFB4AB)
val GreenContainerDark = Color(0xFF1F4D2A)
val OnGreenContainerDark = Color(0xFFB7F0C2)
val BrownContainerDark = Color(0xFF5A3F22)
val OnBrownContainerDark = Color(0xFFF5DDC4)
val GoldContainerDark = Color(0xFF594100)
val OnGoldContainerDark = Color(0xFFFFE08A)
val OutlineDark = Color(0xFF8C9384)
val OutlineVariantDark = Color(0xFF3F463B)
val SurfaceLowestDark = Color(0xFF0E130E)
val SurfaceLowDark = Color(0xFF1A201A)
val SurfaceContainerDark = Color(0xFF1E251E)
val SurfaceHighDark = Color(0xFF283028)
val SurfaceHighestDark = Color(0xFF323A31)
